---
name: Cisco Vision SNMP2MQTT
version: 0.5.0-alpha1
slug: cisco_vision_snmp2mqtt
description: Cisco Vision SNMP to MQTT bridge for Home Assistant
url: https://github.com/zemerdon/cisco-vision-snmp2mqtt

arch:
  - amd64
  - aarch64

image: ghcr.io/zemerdon/cisco-vision-snmp2mqtt-addon

startup: application
boot: auto
init: false

map:
  - addons:rw
  - all_addon_configs:rw
  - config:rw
  - share:rw
  - ssl:rw

services:
  - mqtt:need

homeassistant: 2026.7.1

panel_icon: mdi:cog-transfer-outline
panel_title: Cisco Vision

options:
  mqtt:
    host: "localhost"
    port: 1883

  targets_path: "/config/addons_config/cisco_vision_snmp2mqtt/targets.yaml"

  homeassistant:
    discovery: false
    prefix: "homeassistant"

schema:
  mqtt:
    host: str?
    port: port?
    username: str?
    password: str?
    client_id: str?
    keepalive: int?
    clean: bool?
    retain: bool?
    qos: int?
    base_topic: str?
    host_name_as_target: bool?
    ca: str?
    cert: str?
    key: str?
    reject_unauthorized: bool?

  targets_path: str

  homeassistant:
    discovery: bool?
    prefix: str?

  log: list(debug|info|warning|error)?
